
const MAD_LIB = getLongMadLib(); // You can try using both getShortMadLib() and getLongMadLib()

const WORD_REGEX = /^[a-zA-Z]+$/;
const PROPER_NOUN_REGEX = /^[A-Z][a-zA-Z]*$/;
const ADJECTIVE_REGEX = /^[a-zA-Z]*[yY]$/;
const QUOTE_REGEX = /^(".*"|'.*')$/;

const WORD_ERROR = "Please type 1 or more letters, without spaces or special characters.";
const NOUN_ERROR = "Please type 1 or more letters, without special characters, starting with a capital letter.";
const ADJ_ERROR = "Please type 1 or more letters, without special characters, ending with a y.";
const QUOTE_ERROR = "Please type 1 or more characters between single or double quotes.";

/**
 * This function is done for you.
 * This function is called when the page is initially loaded.
 * It will generate inputs based on the contents of the MAD_LIB.fillers list.
 * Each input has an associated label and error text that begins as empty.
 */
function setup() {
    let parentNode = document.getElementById("madlib-questions");

    for(let i = 0; i < MAD_LIB.fillers.length; i++) {
        let currLib = MAD_LIB.fillers[i];

        let newDivNode = document.createElement("div");
        newDivNode.className = "mb-2"

        let newInputNode = document.createElement("input");
        newInputNode.id = currLib.id + "-input";
        newInputNode.style.maxWidth = "25em";
        newInputNode.className = "form-control"
        newInputNode.placeholder = currLib.exampleText;
        
        let newLabelNode = document.createElement("label");
        newLabelNode.htmlFor = currLib.id + "-input";
        newLabelNode.innerText = currLib.friendlyText;

        let newErrorTextNode = document.createElement("p");
        newErrorTextNode.id = currLib.id + "-error-text";
        newErrorTextNode.style.color = "red";
        newErrorTextNode.innerText = "";

        newDivNode.appendChild(newLabelNode);
        newDivNode.append(newInputNode);
        newDivNode.append(newErrorTextNode);

        parentNode.appendChild(newDivNode);
    }
}

/**
 * This function is done for you.
 * This function is called anytime the user presses the "Generate!" button.
 * It first checks if the given inputs are valid. If they are valid,
 * the madlib is generated by calling the generateLib function.
 */
function generate() {
    if (validate()) {
        generateLib();
        alert("Success! Please see below for your MadLib :)");
    } else {
        alert("Uh oh, please check your form submission.")
    }
}

/**
 * This function is called by generate any time the user requests
 * generation and validation passes. Generate the `madlib-result` div
 * such that any existing HTML is replaced with the newest madlib contents.
 */
function generateLib() {
    const resultDiv = document.getElementById("madlib-result");
    resultDiv.innerHTML = "";

    resultDiv.replaceChildren();

    let currentP = document.createElement("p");
    resultDiv.appendChild(currentP);

    for (let i = 0; i < MAD_LIB.text.length; i++) {
        let segment = MAD_LIB.text[i];

        if (segment.segmentType === "static") {
            // Add plain text to the current paragraph
            currentP.innerText += segment.text;
        } 
        else if (segment.segmentType === "fillable") {
            // Find the user's answer and add it to the text
            let userInput = document.getElementById(segment.id + "-input").value;
            currentP.innerText += userInput;
        } 
        else if (segment.segmentType === "newline") {
            // Encountered a newline: Start a brand new paragraph element
            currentP = document.createElement("p");
            resultDiv.appendChild(currentP);
        }
    }
}

window.onload = setup;

/**
 * This function should check if any of the inputs have validation errors.
 * For each input, if it has validation errors, set the appropriate error text.
 * Otherwise, reset any error text that may exist. Use error text appropriate to
 * each form control, for exdample if validation fails on a quote, the error text
 * should say 'Please type 1 or more characters between quotes.' If the validation fails 
 * on a word, the error text should say 'Please type 1 or more letters, without spaces.'
 * 
 * Be sure to return true or false! Return true if all inputs are valid,
 * otherwise return false if ANY input is invalid.
 * 
 * @returns {boolean} true if form is valid, false otherwise.
 */
function validate() {
    let isValid = true;
    
    // TODO: If any inputs are invalid, set their error text.
    //       After checking ALL inputs, return true/false if
    //       the entire form was valid or not.
    for(let i = 0; i < MAD_LIB.fillers.length; i++) {
        let currLib = MAD_LIB.fillers[i];
        let inputE1 = document.getElementById(currLib.id + "-input");
        let errorE1 = document.getElementById(currLib.id + "-error-text");
        let val = inputE1.value;
        
        let isFieldValid = true;
        let errorMessage = "";

        if (currLib.type === "word") {
            isFieldValid = WORD_REGEX.test(val);
            errorMessage = WORD_ERROR;
        } else if (currLib.type === "properNoun") {
            isFieldValid = PROPER_NOUN_REGEX.test(val);
            errorMessage = NOUN_ERROR;
        } else if (currLib.type === "adjective") {
            isFieldValid = ADJECTIVE_REGEX.test(val);
            errorMessage = ADJ_ERROR;
        } else if (currLib.type === "quote") {
            // Regex check + ensure length > 2 (so "" or '' is invalid)
            isFieldValid = QUOTE_REGEX.test(val) && val.length > 2;
            errorMessage = QUOTE_ERROR;
        }

        if (!isFieldValid) {
            errorE1.innerText = errorMessage;
            inputE1.classList.add("is-invalid");
            isValid = false; // "Trip the wire" so the whole form fails
        } else {
            errorE1.innerText = "";
            inputE1.classList.remove("is-invalid");
        }
    }

    return isValid;
}

// Don't remove this! It runs the setup function on page load.
window.onload = setup;
